// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFK59MVbT4JNcF1sHmzOjyugwV3WaNIJ4',
    appId: '1:1041082884941:web:2136d98bda64fac17a4d04',
    messagingSenderId: '1041082884941',
    projectId: 'ipssi-flutter-projet',
    authDomain: 'ipssi-flutter-projet.firebaseapp.com',
    storageBucket: 'ipssi-flutter-projet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GEWMtsvyliHkwvyH34XMSoawbi5vElw',
    appId: '1:1041082884941:android:d737b696e7ed5f947a4d04',
    messagingSenderId: '1041082884941',
    projectId: 'ipssi-flutter-projet',
    storageBucket: 'ipssi-flutter-projet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBQpitcwNoR5cZoI5PvWd-5HznJgE-dM',
    appId: '1:1041082884941:ios:ed481ee54f1a3f6a7a4d04',
    messagingSenderId: '1041082884941',
    projectId: 'ipssi-flutter-projet',
    storageBucket: 'ipssi-flutter-projet.appspot.com',
    iosClientId: '1041082884941-p9k7ugar0b1kptsdokohodjo4giabrgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBQpitcwNoR5cZoI5PvWd-5HznJgE-dM',
    appId: '1:1041082884941:ios:85069229d5f5365a7a4d04',
    messagingSenderId: '1041082884941',
    projectId: 'ipssi-flutter-projet',
    storageBucket: 'ipssi-flutter-projet.appspot.com',
    iosClientId: '1041082884941-26vao9n5jgi83mgu33oo8mtlra4v5cf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233.RunnerTests',
  );
}
